<template>
  <v-card class="loginForm rounded-lg pa-6 boxShadowed">
    <v-tabs background-color="transparent" v-model="tabs" fixed-tabs>
      <v-tab>Connexion</v-tab>
      <v-tab>Inscription</v-tab>
    </v-tabs>
    <v-tabs-items class="loginForm__tabsItem" v-model="tabs">
      <v-tab-item>
        <v-card color="transparent" flat class="pa-5">
          <v-form ref="formLogin" v-model="validLoginForm" lazy-validation>
            <v-text-field
              id="emailLogin"
              v-model="emailLogin"
              :rules="emailRules"
              label="E-mail"
              @click="resetForm('emailLogin', 'E-mail');"
              required
            ></v-text-field>
            <v-text-field
              id="passwordLogin"
              v-model="passwordLogin"
              :append-icon="showPassword ? 'visibility' : 'visibility_off'"
              :type="showPassword ? 'text' : 'password'"
              @click:append="showPassword = !showPassword"
              :rules="passwordRules"
              label="Mot de passe"
              @click="resetForm('passwordLogin', 'Mot de passe');"
              required
            ></v-text-field>
            <v-btn
              :loading="loadingLogin"
              block
              :disabled="!validLoginForm || loadingLogin"
              color="primary"
              class="mr-4 mt-5"
              @click="login();"
            >Connexion</v-btn>
          </v-form>
        </v-card>
      </v-tab-item>

      <v-tab-item>
        <v-card color="transparent" flat class="pa-5">
          <v-form ref="formSignup" v-model="validSignupForm" lazy-validation>
            <v-text-field
              id="emailSignup"
              v-model="emailSignup"
              :rules="emailRules"
              label="E-mail"
              required
            ></v-text-field>
            <v-text-field
              id="passwordSignup"
              v-model="passwordSignup"
              :append-icon="showPassword ? 'visibility' : 'visibility_off'"
              :type="showPassword ? 'text' : 'password'"
              @click:append="showPassword = !showPassword"
              :rules="passwordRules"
              label="Mot de passe"
              required
            ></v-text-field>
            <v-text-field
              v-model="nameSignup"
              :counter="30"
              :rules="nameRules"
              label="Nom d'affichage"
              required
            ></v-text-field>
            <v-btn
              block
              :loading="loadingSignup"
              :disabled="!validSignupForm || loadingSignup"
              color="primary"
              class="mr-4 mt-5"
              @click="signup();"
            >S'inscrire</v-btn>
          </v-form>
        </v-card>
      </v-tab-item>
    </v-tabs-items>

    <v-snackbar v-model="snackbar" :timeout="4000" color="red darken-3">
      {{ snackbarMsg }}
      <template v-slot:action="{ attrs }">
        <v-btn color="white" text v-bind="attrs" @click="snackbar = false">Fermer</v-btn>
      </template>
    </v-snackbar>
  </v-card>
</template>

<script>
export default {
  data: () => ({
    validLoginForm: true,
    validSignupForm: true,
    loadingLogin: false,
    loadingSignup: false,
    snackbar: false,
    snackbarMsg: "",
    nameSignup: "",
    nameRules: [
      (v) => !!v || "Veuillez renseigner votre nom d'affichage",
      (v) =>
        (v && v.length <= 30) ||
        "Le nom d'affichage doit contenir moins de 30 caractères",
    ],
    emailSignup: "",
    emailLogin: "autogenerated3@groupomania.fr",
    emailRules: [
      (v) => !!v || "Veuillez renseigner votre adresse email",
      (v) => /.+@.+\..+/.test(v) || "L'adresse email doit être valide",
    ],
    passwordSignup: "",
    passwordLogin: "Test1234",
    passwordRules: [
      (v) => !!v || "Veuillez renseigner votre mot de passe",
      (v) =>
        (v && v.length >= 8) ||
        "Votre mot de passe doit contenir au moins 8 caractères",
    ],
    tabs: null,
    showPassword: false,
  }),

  methods: {
    login() {
      this.$refs.formLogin.validate();
      if (this.emailLogin && this.passwordLogin) {
        this.loadingLogin = true;
        let loginData = {
          email: this.emailLogin,
          password: this.passwordLogin,
        };
        fetch(`${process.env.VUE_APP_ROOT_API}api/user/auth/login`, {
          method: "POST",
          credentials: "include",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify(loginData),
        })
          .then((response) => {
            if (response.ok) {
              response.json().then((response) => {
                this.$store.dispatch("logIn", response);
                this.$router.push({ name: "Home" });
              });
            } else {
              response.json().then((error) => {
                switch (error.code) {
                  case 1:
                    this.emailLogin = "";
                    document.querySelector("label[for=emailLogin]").innerHTML =
                      error.message;
                    break;
                  case 2:
                    this.passwordLogin = "";
                    document.querySelector(
                      "label[for=passwordLogin]"
                    ).innerHTML = error.message;
                    break;
                  default:
                    this.snackbarMsg = error.message;
                    this.snackbar = true;
                    break;
                }
              });
            }
            this.loadingLogin = false;
          })
          .catch((error) => {
            console.log("Erreur lors du fetch : " + error.message);
            this.snackbarMsg = error.message;
            this.snackbar = true;
            this.loadingLogin = false;
          });
      }
    },

    signup() {
      this.$refs.formSignup.validate();
      if (this.emailSignup && this.passwordSignup && this.nameSignup) {
        this.loadingSignup = true;
        let signupData = {
          email: this.emailSignup,
          password: this.passwordSignup,
          nickname: this.nameSignup,
        };
        fetch(`${process.env.VUE_APP_ROOT_API}api/user/auth/signup`, {
          method: "POST",
          credentials: "include",
          headers: {
            "Content-Type": "application/json",
          },
          body: JSON.stringify(signupData),
        })
          .then((response) => {
            if (response.ok) {
              response.json().then((response) => {
                this.$store.dispatch("logIn", response);
                this.$router.push({ name: "Home" });
              });
            } else {
              response.json().then((error) => {
                if (error.code) {
                  if (error.code.includes("1")) {
                    console.log("code 1");
                  }
                  if (error.code.includes("2")) {
                    console.log("code 2");
                  }
                  if (error.code.includes("3")) {
                    console.log("code 3");
                  }
                }
                console.log(error); // GESTION ERREURS A TERMINER
              });
            }
            this.loadingSignup = false;
          })
          .catch((error) => {
            console.log("Erreur lors du fetch : " + error.message);
            this.snackbarMsg = error.message;
            this.snackbar = true;
            this.loadingSignup = false;
          });
      }
    },

    resetForm(input, text) {
      document.querySelector(`label[for=${input}]`).innerHTML = text;
    },
  },
};
</script>

<style lang="scss" scoped>
.loginForm {
  max-width: 420px;
  margin: auto;
  &__tabsItem {
    background-color: transparent !important;
  }
}
</style>